/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rstat.h"
#include <string.h>
#define FSHIFT  8   /* bits to right of fixed binary point */
#define FSCALE  (1<<FSHIFT)

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

statsusers *
rstatproc_stats_5(argp, clnt)
	void *argp;
	CLIENT *clnt;
{
	static statsusers clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, RSTATPROC_STATS, xdr_void, argp, xdr_statsusers, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

u_int *
rstatproc_havedisk_5(argp, clnt)
	void *argp;
	CLIENT *clnt;
{
	static u_int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, RSTATPROC_HAVEDISK, xdr_void, argp, xdr_u_int, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

statsvar *
rstatproc_stats_4(argp, clnt)
	void *argp;
	CLIENT *clnt;
{
	static statsvar clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, RSTATPROC_STATS, xdr_void, argp, xdr_statsvar, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

u_int *
rstatproc_havedisk_4(argp, clnt)
	void *argp;
	CLIENT *clnt;
{
	static u_int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, RSTATPROC_HAVEDISK, xdr_void, argp, xdr_u_int, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

statstime *
rstatproc_stats_3(argp, clnt)
	void *argp;
	CLIENT *clnt;
{
	static statstime clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, RSTATPROC_STATS, xdr_void, argp, xdr_statstime, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

u_int *
rstatproc_havedisk_3(argp, clnt)
	void *argp;
	CLIENT *clnt;
{
	static u_int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, RSTATPROC_HAVEDISK, xdr_void, argp, xdr_u_int, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

statsswtch *
rstatproc_stats_2(argp, clnt)
	void *argp;
	CLIENT *clnt;
{
	static statsswtch clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, RSTATPROC_STATS, xdr_void, argp, xdr_statsswtch, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

u_int *
rstatproc_havedisk_2(argp, clnt)
	void *argp;
	CLIENT *clnt;
{
	static u_int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, RSTATPROC_HAVEDISK, xdr_void, argp, xdr_u_int, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

stats *
rstatproc_stats_1(argp, clnt)
	void *argp;
	CLIENT *clnt;
{
	static stats clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, RSTATPROC_STATS, xdr_void, argp, xdr_stats, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

u_int *
rstatproc_havedisk_1(argp, clnt)
	void *argp;
	CLIENT *clnt;
{
	static u_int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, RSTATPROC_HAVEDISK, xdr_void, argp, xdr_u_int, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}
